Agents bsn link
tweedegolf/veilig-bellen pull request #17
Opened 2020-08-25 06:51 UTC by hdoordt

Adds am optional configuration to public-agents, which maps irma attributes to url templates, in which the attribute value is inserted , and of which a link is created in the agent frontend

2020-08-25 10:05 UTC, Lucus16 requested changes

2020-08-25 10:05 UTC, Lucus16 commented on frontend-agents/src/components/ContactInfo.jsx
> +                            key in urlTemplates
This will throw when `urlTemplates` is `false`, right? Maybe it should default to an empty dict instead?

2020-08-25 10:35 UTC, hdoordt commented on frontend-agents/src/components/ContactInfo.jsx
> +                            key in urlTemplates
Good call, added a falsiness check

2020-08-27 09:41 UTC, Lucus16 approved these changes

2020-08-27 10:26 UTC, merged